### ISSUE TITLE
Fix reconnect after offline for multiple minutes

### ISSUE THREAD

**Issue by bdraco** [bdraco/aiolip#1]
```
21-02-09 07:17:56 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiolip/__init__.py", line 163, in async_run
    await self._async_run_once()
  File "/usr/local/lib/python3.8/site-packages/aiolip/__init__.py", line 186, in _async_run_once
    if isinstance(read_task.exception(), asyncio.TimeoutError) or isinstance(
asyncio.exceptions.InvalidStateError: Exception is not set.
2021-02-09 07:17:56 DEBUG (MainThread) [aiolip] Connecting to 192.168.107.77

2021-02-09 07:17:59 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiolip/__init__.py", line 137, in _async_keep_alive_or_reconnect
    await self._async_disconnected()
  File "/usr/local/lib/python3.8/site-packages/aiolip/__init__.py", line 108, in _async_disconnected
    await self._async_connect(self._host)
  File "/usr/local/lib/python3.8/site-packages/aiolip/__init__.py", line 69, in _async_connect
    reader, writer = await asyncio.wait_for(
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.107.77', 23)
```

**Comment by bdraco** [comment]
Fixed in latest release
